detekt:
  build:
    maxIssues: 0
  config:
    validation: true
  reports:
    xml:
      enabled: true
    html:
      enabled: true
    txt:
      enabled: false
    sarif:
      enabled: false

processors:
  active: true

rules:
  comments:
    EndOfSentenceFormat:
      active: false

  style:
    MagicNumber:
      active: false
    WildcardImport:
      active: true
    MaxLineLength:
      active: true
      maxLineLength: 120

  complexity:
    LongParameterList:
      active: true
      threshold: 8
    TooManyFunctions:
      active: false
